Don't let bad docker-compose.yml ruin a good stop
BOSH used to get angry during a `monit stop` of the `docker` job if the
docker-compose.yml recipe was bad (mismatched version, was actually a
quoted string, bad YAML contents, etc.).

Since this happens quite a lot, especially when I'm involved, I finally
fixed this so that a compose down wasn't the end of the world, and we
could force-kill the containers and be done with it.

diff --git a/jobs/docker/templates/bin/docker b/jobs/docker/templates/bin/docker
--- a/jobs/docker/templates/bin/docker
+++ b/jobs/docker/templates/bin/docker
@@ -55,7 +55,7 @@ case $1 in
     <% if !p('recipe', {}).empty? %>
     pushd $JOB_DIR/etc/running >/dev/null 2>&1
     echo "[$(date)] $BIN/$$: shutting down docker-compose'd containers..."
-    docker-compose down
+    docker-compose down || true # borked compose recipes may fail to down...
     <% else %>
     echo "[$(date)] $BIN/$$: no docker-compose recipe detected; nothing to shut down..."
     <% end %>
